# Fuzzy Probabilistic C-Means (FPCM) Clustering

### LK-07 Kelompok 3

- Zahra Asma Annisa - 195150201111058

- Muhammad Fathur Rahman Khairul 195150200111056

- Duwi Purnama Sidik - 195150219111001

- Oktaviani Dwi Nur Aini - 195150219111002

#### 1. Import Library

In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime as time

#### 2. Load Dataset

In [ ]:
!git clone https://github.com/ZahraAsmaA/datasets.git

Cloning into 'datasets'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 4), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), done.


In [ ]:
df = pd.read_csv("/content/datasets/Fish.csv")

In [ ]:
start = time.now()

df = df.sample(frac=1).reset_index(drop=True)

# df

df_copy = df.copy()
df_copy.pop('No')
df_copy.pop('Species')
df_copy

Weight  Length1  Length2  Length3   Height   Width
0    1000.0     33.5     37.0     42.6  18.9570  6.6030
1     510.0     40.0     42.5     45.5   6.8250  4.4590
2     600.0     29.4     32.0     37.2  14.9544  5.1708
3      19.7     13.2     14.3     15.2   2.8728  2.0672
4     725.0     31.8     35.0     40.9  16.3600  6.0532
..      ...      ...      ...      ...      ...     ...
154   610.0     30.9     33.5     38.6  15.6330  5.1338
155  1000.0     37.3     40.0     43.5  12.3540  6.5250
156  1650.0     59.0     63.4     68.0  10.8120  7.4800
157  1000.0     41.1     44.0     46.6  12.4888  7.5958
158    12.2     11.5     12.2     13.4   2.0904  1.3936

[159 rows x 6 columns]

#### 3. Normalisasi Fitur Dataset (Min-Max)
normalized_x = (x - min) / (max - min)

In [ ]:
def minmax(df):
    columns = df.columns[:]
    for column in columns:
        max = df[column].max()
        min = df[column].min()
        df[column] = (df[column] - min)/(max - min)
    return df.to_numpy()

norm_df = minmax(df_copy)
norm_df

array([[6.06060606e-01, 5.04854369e-01, 5.20000000e-01, 5.70945946e-01,
        1.00000000e+00, 7.83068336e-01],
       [3.09090909e-01, 6.31067961e-01, 6.20000000e-01, 6.19932432e-01,
        2.95822063e-01, 4.80858142e-01],
       [3.63636364e-01, 4.25242718e-01, 4.29090909e-01, 4.79729730e-01,
        7.67677002e-01, 5.81190798e-01],
       [1.19393939e-02, 1.10679612e-01, 1.07272727e-01, 1.08108108e-01,
        6.64244338e-02, 1.43718990e-01],
       [4.39393939e-01, 4.71844660e-01, 4.83636364e-01, 5.42229730e-01,
        8.49262273e-01, 7.05570591e-01],
       [9.69696970e-02, 2.52427184e-01, 2.56363636e-01, 2.78716216e-01,
        3.07918229e-01, 3.90829387e-01],
       [2.36363636e-01, 3.90291262e-01, 3.92727273e-01, 4.42567568e-01,
        6.35083524e-01, 5.13419035e-01],
       [4.15151515e-01, 5.14563107e-01, 5.10909091e-01, 5.10135135e-01,
        5.31244558e-01, 8.19857916e-01],
       [5.57575758e-01, 5.33980583e-01, 5.47272727e-01, 5.96283784e-01,
        9.46594616e-01, 

#### 4. Proporsi Data
- Data Training = 70%
- Data Testing  = 30%

In [ ]:
proportion = int(len(norm_df)*0.7)             # 70% dataset

data_train = norm_df[:proportion]
data_test = norm_df[proportion:]

print('Data Latih :', len(data_train),'\nData Uji  :',len(data_test))

Data Latih : 111 
Data Uji  : 48


In [ ]:
data_train

array([[6.06060606e-01, 5.04854369e-01, 5.20000000e-01, 5.70945946e-01,
        1.00000000e+00, 7.83068336e-01],
       [3.09090909e-01, 6.31067961e-01, 6.20000000e-01, 6.19932432e-01,
        2.95822063e-01, 4.80858142e-01],
       [3.63636364e-01, 4.25242718e-01, 4.29090909e-01, 4.79729730e-01,
        7.67677002e-01, 5.81190798e-01],
       [1.19393939e-02, 1.10679612e-01, 1.07272727e-01, 1.08108108e-01,
        6.64244338e-02, 1.43718990e-01],
       [4.39393939e-01, 4.71844660e-01, 4.83636364e-01, 5.42229730e-01,
        8.49262273e-01, 7.05570591e-01],
       [9.69696970e-02, 2.52427184e-01, 2.56363636e-01, 2.78716216e-01,
        3.07918229e-01, 3.90829387e-01],
       [2.36363636e-01, 3.90291262e-01, 3.92727273e-01, 4.42567568e-01,
        6.35083524e-01, 5.13419035e-01],
       [4.15151515e-01, 5.14563107e-01, 5.10909091e-01, 5.10135135e-01,
        5.31244558e-01, 8.19857916e-01],
       [5.57575758e-01, 5.33980583e-01, 5.47272727e-01, 5.96283784e-01,
        9.46594616e-01, 

In [ ]:
data_test

array([[0.15151515, 0.35728155, 0.35636364, 0.34797297, 0.35359809,
        0.44494249],
       [0.00739394, 0.08932039, 0.08363636, 0.08445946, 0.0318424 ,
        0.02934709],
       [0.3030303 , 0.66990291, 0.66545455, 0.66216216, 0.30365787,
        0.54245602],
       [0.14666667, 0.30485437, 0.30909091, 0.35810811, 0.56833405,
        0.41897835],
       [0.42424242, 0.47378641, 0.48363636, 0.53547297, 0.84232613,
        0.6401387 ],
       [0.07878788, 0.22912621, 0.23454545, 0.23648649, 0.27022509,
        0.35047361],
       [0.22      , 0.36504854, 0.37454545, 0.41722973, 0.63856611,
        0.48036479],
       [0.42424242, 0.44466019, 0.44727273, 0.49831081, 0.76222096,
        0.59734438],
       [0.06666667, 0.22330097, 0.22909091, 0.23141892, 0.23008834,
        0.35343369],
       [0.03121212, 0.14563107, 0.14181818, 0.14189189, 0.16623521,
        0.2232747 ],
       [0.3369697 , 0.47572816, 0.47454545, 0.46790541, 0.49499669,
        0.75269226],
       [0.03333333, 0

#### 5. Method Inisialisasi Matriks V Awal (Disesuaikan Dengan Metode FCM)

In [ ]:
def set_V_awal(x, u, c, w):
    v = np.zeros([c, len(x)])

    for k in range(len(v)):
        for j in range(len(v[k])):
            v[k][j] = (sum(((u[i][k]**w) * x[i][j]) for i in range(len(x)))) / (sum((u[i][k]**w) for i in range(len(u))))

    return v

#### 6. Method Update Nilai Matriks t

In [ ]:
def update_t(t, x, v, n):
    for i in range(len(t)):
        for k in range(len(t[i])):
            t[i][k] = ((sum((x[i]-v[k])**2))**((-1)/(n-1))) \
                    / (sum(((sum((x[i]-v[k])**2))**((-1)/(n-1))) for i in range(len(x))))

    return t

#### 7. Method Update Nilai Matriks V

In [ ]:
def update_V(v, x, u, t, w, n):
    for k in range(len(v)):
        for j in range(len(v[k])):
            v[k][j] = (sum((((u[i][k]**w) + (t[i][k]**n)) * x[i][j]) for i in range(len(x)))) \
                    / (sum(((u[i][k]**w) + (t[i][k]**n)) for i in range(len(x))))

    return v

#### 8. Method Update Nilai Matriks U

In [ ]:
def update_U(u, x, v, w):
    for i in range(len(u)):
        for k in range(len(u[i])):
            u[i][k] = ((sum((x[i]-v[k])**2))**((-1)/(w-1))) \
                    / (sum(((sum((x[i]-v[k])**2))**((-1)/(w-1))) for i in range(len(x))))

    return u

#### 9. Method Perhitungan Fungsi Objektif

In [ ]:
def get_P1(x, v, u, t, w, n):
    return sum((sum(((sum((x[i]-v[k])**2))) * ((u[i][k]**w) + (t[i][k]**n)) \
           for k in range(len(v)))) for i in range(len(x)))

#### 10. Method FPCM (Training)

In [ ]:
def FPCM(x, c, w, n, max_i, P0, e):
    list_i = []
    list_P0 = []
    list_P1 = []
    list_abs_P1_min_P0 = []

    U = np.random.rand(len(x), c)
    V = set_V_awal(x=x, u=U, c=c, w=w)
    t = np.zeros(U.shape)
    t = update_t(t=t, x=x, v=V, n=n)

    i = 1
    while(i <= max_i):
        P1 = get_P1(x=x, v=V, u=U, t=t, w=w, n=n)
        abs_P1_min_P0 = abs(P1 - P0)

        list_i.append(i)
        list_P0.append(P0)
        list_P1.append(P1)
        list_abs_P1_min_P0.append(abs_P1_min_P0)

        V = update_V(v=V, x=x, u=U, t=t, w=w, n=n)
        U = update_U(u=U, x=x, v=V, w=w)
        t = update_t(t=t, x=x, v=V, n=n)

        if abs_P1_min_P0 < e:
            break
        else:
            P0 = P1
            i += 1

    p_df = pd.DataFrame(list(zip(list_i, list_P1, list_P0, list_abs_P1_min_P0)), columns=['iterasi', 'P1', 'P0', '|P1-P0|'])

    return V,p_df

#### 11. Method Penentuan Cluster (Testing)
Menghitung jarak antara data testing dengan pusat cluster (V) yang telah didapatkan dari training. Penghitungan jarak menggunakan metode Euclidean. Cluster ditentukan dengan jarak terdekat dengan pusat cluster (V).

In [ ]:
def get_cluster(x, v):
    data = [(i+1) for i in range(len(x))]
    fitur = [('F' + str(m+1)) for m in range(len(x[0]))]
    cluster = [(np.argmin([np.sqrt(sum((xi-vi)**2)) for vi in v]) + 1) for xi in x]

    cluster_df = pd.DataFrame(x, columns=fitur)
    cluster_df['Cluster'] = cluster
    cluster_df.insert(0, 'Data', data)

    return cluster_df

#### 12. Melakukan Training

In [ ]:
V_train, P_df = FPCM(x=data_train, c=2, w=2, n=2, max_i=10, P0=0, e=0.00001)

IndexError: ignored

In [ ]:
# pusat cluster (1 data pertama)
V_train[:1],V_train.shape

In [ ]:
# fungsi objektif setiap iterasi
P_df

#### 13. Melakukan Testing

In [ ]:
cluster_df = get_cluster(x=data_test, v=V_train)

In [ ]:
# hasil clustering (5 data teratas)
cluster_df.head()

In [ ]:
# jumlah data tiap cluster
cluster_df.groupby(['Cluster'])['Data'].count().reset_index().rename(columns={"Data" : "Count (Data)"})

In [ ]:
# simpan hasil clustering dalam format *.csv
cluster_df.to_csv('hasil_clustering_FPCM.csv', index=False)

In [ ]:
# read hasil_clustering_FPCM.csv
# pd.read_csv('hasil_clustering_FPCM.csv').head()

#### 14. Evaluasi Hasil Clustering (Silhouette Coefficient)
Silhouette Coefficient merupakan metode evaluasi untuk clustering dengan rentang nilai -1 sampai dengan 1. Apabila nilai silhouette semakin mendekati 1, maka sistem clustering dapat dikatakan semakin baik. Nilai silhouette adalah 0 apabila hanya terdapat 1 cluster.

In [ ]:
import Silhouette_Coefficient as sc

global_s, local_s_df = sc.get_Silhouette(cluster_df)

In [ ]:
# nilai silhouette pada setiap cluster
local_s_df

In [ ]:
# nilai evaluasi keseluruhan sistem clustering
print('Silhouette Coefficient:',global_s)

#### 15. Waktu Eksekusi Program
Terhitung dari waktu melakukan load dataset sampai selesai melakukan evaluasi hasil clustering.

In [ ]:
t = time.now() - start
print('Waktu Eksekusi:',str(t.seconds)+","+str(t.microseconds)[:3],'detik')